#!/usr/bin/env python

import os
import sys
import time # for sleep
import random

def main():
    max_line = 100
    for line_num in range(0, max_line):
        for i in range(0, 32):
            x = random.randint(0, 1)
            if x == 1:
                sys.stdout.write('H')
            else:
                sys.stdout.write('L')
        print

if __name__ == '__main__':
    main()
